from app.exceptions.repositories.base import BaseRepoError


class AlreadyExistsRepoError(BaseRepoError):
    pass
