from app.common.exceptions.services.base import BaseServiceError


class AlreadyExistsServiceError(BaseServiceError):
    pass
