from app.common.exceptions.repositories.base import BaseRepoError


class AlreadyExistsRepoError(BaseRepoError):
    pass
